export const SHOWCATID = 'cats/setCatsId'
export const SET_PROFILEBYID = 'profile/setProfileById'
export const SHOWGETCAT = 'cats/setCats'
export const SET_RANDOMCARD = 'randomCard/setRandomCard'
export const DELETE_PROFILEBYID_CAT = 'profile/setProfileByIdCat'